export const SET_LOCALITY = 'SET_LOCALITY'
export const SET_MAP_VIEW = 'SET_MAP_VIEW'

export const SET_GEOLOCATION = 'SET_GEOLOCATION'
export const DISPLAY_DIRECTIONS = 'DISPLAY_DIRECTIONS'
export const CLEAR_DIRECTIONS = 'CLEAR_DIRECTIONS'

export const ADD_REVIEW = 'ADD_REVIEW'

export const ADD_WAYPOINTS = 'ADD_WAYPOINTS'

export const SET_VENUE = 'SET_VENUE'
export const CLEAR_VENUE = 'CLEAR_VENUE'

export const SET_CATEGORY = 'SET_CATEGORY'
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY'

export const CLEAR_APP = 'CLEAR_APP'
